name: "ESP32 HCI Proxy"
version: "0.0.1"
slug: "esp32_hci_proxy"
description: "An ESP32 Bluetooth Proxy"
url: "https://github.com/BogdanDIA/esp32-hci-proxy-addon"
stage: experimental
host_network: true
host_dbus: true
# homeassistant_api: true
privileged: [NET_ADMIN]
uart: true
arch:
  - aarch64
  - amd64
hassio_role: homeassistant
init: false
map:
  - share:rw
startup: services
options:
  ble_btattach_device: ""
  ble_btattach_baud: "921600"
  ble_btattach_protocol: "h4"
  ble_btattach_hwflow: "0"
  ble_sudpfwd_device: ""
  ble_sudpfwd_baud: "921600"
  ble_sudpfwd_server: ""
  ble_sudpfwd_port: "3333"
  ble_sudpfwd_hwflow: "0"
  ble_sudpfwd_flowdebug: "0"
  ble_sudpfwd_datadebug: "0"

schema:
  ble_btattach_device: str 
  ble_btattach_baud: str? 
  ble_btattach_protocol: str?
  ble_btattach_hwflow: "int(0,1)" 
  ble_sudpfwd_device: str
  ble_sudpfwd_baud: str? 
  ble_sudpfwd_server: str 
  ble_sudpfwd_port: "int(1024,65535)"
  ble_sudpfwd_hwflow: "int(0,1)"
  ble_sudpfwd_flowdebug: "int(0,1)"
  ble_sudpfwd_datadebug: "int(0,1)"

  debug_tests: bool?
  debug: bool?

# ingress: true
# panel_icon: mdi:forward
# backup_exclude:
  # - /data/gnugpg
  # - /data/password-store
# hassio_api: true
